version: '3'
services:
  redis:
    build:
      context: ./
      dockerfile: redis.Dockerfile
    image: seckill/redis:1.0
    container_name: redis
    hostname: redis
    networks:
      - default
      - app_net
    ports:
      - "6379:6379"  
networks:
  app_net:
    external: true   
  
      
  