version: '3'
services:
  kafka01:
    build:
      context: ./
      dockerfile: kafka.Dockerfile
    image: seckill/kafka:1.0
    restart: always
    container_name: kafka01
    hostname: kafka01
    ports:
      - "9092:9092"
    networks:
      - default
      - app_net    
    environment:
      ZOOKEEPER_CONNECT: zookeeper01:2181,zookeeper02:2182
      BROKER_ID: 1
      LISTENERS: listeners=PLAINTEXT:\/\/kafka01:9092
      ADVERTISED_LISTENERS: advertised.listeners=PLAINTEXT:\/\/kafka01:9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - 9092
networks:
  app_net:
    external: true  
  
      
  