version: '3'
services:
  kafka01:
    build:
      context: ./
      dockerfile: kafka.Dockerfile
    image: seckill/kafka:1.0
    restart: always
    container_name: kafka01
    hostname: kafka01
    ports:
      - "9092:9092"
    environment:
      ZOOKEEPER_CONNECT: ${ZOO_SERVERS} 
      BROKER_ID: 1
      LISTENERS: listeners=PLAINTEXT:\/\/kafka01:9092
      ADVERTISED_LISTENERS: advertised.listeners=PLAINTEXT:\/\/${HOST_NAME}:9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - 9092

  
      
  