version: '3'
services:
  zookeeper02:
    build:
      context: ./
      dockerfile: zookeeper.Dockerfile
    image: seckill/zookeeper:1.0
    container_name: zookeeper02
    hostname: zookeeper02
    ports:
      - "2182:2182"
      - "2889:2889"
      - "3889:3889"
    expose:
      - 2182
      - 2889
      - 3889
    environment:
      ZOOKEEPER_PORT: 2182
      ZOOKEEPER_ID: 2
      ZOOKEEPER_SERVERS: ${ZOO_SERVERS}

  
      
  