version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: app.Dockerfile
    image: seckill/app:1.0
    container_name: app
    hostname: app
    ports:
     - "8082:8082"    
    links:
     - mysql 
     - redis
     - kafka0 
  nginx:
    build:
      context: ./
      dockerfile: nginx.Dockerfile
    image: seckill/nginx:1.0
    container_name: nginx
    hostname: nginx
    depends_on:
     - app
    ports:
     - "80:80"  
  redis:
    build:
      context: ./
      dockerfile: redis.Dockerfile
    image: seckill/redis:1.0
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"  
  mysql:
    build:
      context: ./
      dockerfile: mysql.Dockerfile
    image: seckill/mysql:1.0
    container_name: mysql
    hostname: mysql
    ports:
     - "3306:3306"
     #將mysql目錄映射到本地 應根據自己所需要映射的目錄進行修改
    volumes:
     - "/home/DB/mysql/conf:/etc/mysql/conf.d"
     - "/home/DB/mysql/logs:/logs"
     - "/home/DB/mysql/data:/var/lib/mysql"
     
    #設置編碼格式
    command: [
           '--character-set-server=utf8mb4',
           '--collation-server=utf8mb4_unicode_ci'
    ]
    #設置初始化密碼
    environment:
     MYSQL_ROOT_PASSWORD: "root"

  zookeeper0:
    build:
      context: ./
      dockerfile: zookeeper.Dockerfile
    image: seckill/zookeeper:1.0
    container_name: zookeeper0
    hostname: zookeeper0
    ports:
      - "2181:2181"
    expose:
      - 2181
    environment:
      ZOOKEEPER_PORT: 2181
      ZOOKEEPER_ID: 0
      ZOOKEEPER_SERVERS: server.0=zookeeper0:2888:3888

  kafka0:
    build:
      context: ./
      dockerfile: kafka.Dockerfile
    image: seckill/kafka:1.0
    container_name: kafka0
    hostname: kafka0
    ports:
      - "9092:9092"
    environment:
      ZOOKEEPER_CONNECT: zookeeper0:2181
      BROKER_ID: 0
      LISTENERS: listeners=PLAINTEXT:\/\/kafka0:9092
      ADVERTISED_LISTENERS: advertised.listeners=PLAINTEXT:\/\/kafka0:9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
        - zookeeper0
    expose:
      - 9092

  
      
  