version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: app.Dockerfile
    image: seckill/app:1.0
    container_name: app
    hostname: app
    networks:
      - default
      - app_net
    ports:
     - "8082:8082"  
networks:
  app_net:
    external: true  
      
  