version: '3'
services:
  kafka02:
    build:
      context: ./kafka-02
      dockerfile: kafka.Dockerfile
    image: seckill/kafka:1.0
    restart: always
    container_name: kafka02
    hostname: kafka02
    ports:
      - "9093:9093"
    networks:
      - default
      - app_net    
    environment:
      ZOOKEEPER_CONNECT: zookeeper01:2181,zookeeper02:2182 
      BROKER_ID: 2
      LISTENERS: listeners=PLAINTEXT:\/\/kafka02:9093
      ADVERTISED_LISTENERS: advertised.listeners=PLAINTEXT:\/\/kafka02:9093
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - 9093
networks:
  app_net:
    external: true
  
      
  