version: '3'
services:
  zookeeper01:
    build:
      context: ./
      dockerfile: zookeeper.Dockerfile
    image: seckill/zookeeper:1.0
    container_name: zookeeper01
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    networks:
      - default
      - app_net  
    expose:
      - 2181
      - 2888
      - 3888  
    environment:
      ZOOKEEPER_PORT: 2181
      ZOOKEEPER_ID: 1
      ZOOKEEPER_SERVERS: server.1=zookeeper0:2888:3888;2181 server.2=zookeeper02:2889:3889;2182

networks:
  app_net:
    external: true  
  
      
  