version: '3'
services:
  zookeeper01:
    build:
      context: ./zk-01
      dockerfile: zookeeper.Dockerfile
    image: seckill/zookeeper:1.0
    container_name: zookeeper01
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    environment:
      ZOOKEEPER_PORT: 2181
      ZOOKEEPER_ID: 1
      ZOOKEEPER_SERVERS: ${ZOO_SERVERS}

  zookeeper02:
    build:
      context: ./zk-02
      dockerfile: zookeeper.Dockerfile
    image: seckill/zookeeper:1.0
    container_name: zookeeper02
    ports:
      - "2182:2182"
      - "2889:2889"
      - "3889:3889"
    environment:
      ZOOKEEPER_PORT: 2182
      ZOOKEEPER_ID: 2
      ZOOKEEPER_SERVERS: ${ZOO_SERVERS}


  